version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:a784b49bb241291feb47b578a2cb58938d3565dff5b0f6d9bf627036cbd7f419
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.5-alpine@sha256:f30c176a86634baac74a17189dc671b7212b5b47df006042a6a982c9f476cb53
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"