version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:973f078d7d648c88cd211dbaf6edcd17bd18778a6fda0aa9e00a7cf8fba32006
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.5-alpine@sha256:83b450faffac8446818dc9e3f3da9cafb25becbdf732b77fc958e84859c2935d
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"