version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:973f078d7d648c88cd211dbaf6edcd17bd18778a6fda0aa9e00a7cf8fba32006
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.5-alpine@sha256:e46f839001cb722b426f264361ba8743556960bc7088735dd6eb5173ab9e1056
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"