version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:4fa79343710021d300556f57f16721e5cb3859b4bad09ba437d006f5c38efe8e
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.5-alpine@sha256:f1dbca0f5dbc926eccc000967c6b09a441d1808f36b15fde4ae621124c2d3bb4
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"