version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:973f078d7d648c88cd211dbaf6edcd17bd18778a6fda0aa9e00a7cf8fba32006
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.5-alpine@sha256:071d1d197b01507398455139590c7cf04e70621965cd80468898b9ddeb427c4f
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"